package Heathrxw.Xenon.ChaosMod.events;

import Heathrxw.Xenon.ChaosMod.Chaos;
import Heathrxw.Xenon.ChaosMod.ChaosEvent;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;

public class CobwebTrap extends ChaosEvent {
    public void onEnable(String username, Chaos plugin) {
        Player target = (Bukkit.getServer().getPlayer(username));

        if(target !=null) {
            target.getLocation().add(0, -10, 0).getBlock().setType(Material.LAVA);
            target.getLocation().add(0, -10, 1).getBlock().setType(Material.LAVA);
            target.getLocation().add(1, -10, 0).getBlock().setType(Material.LAVA);
            target.getLocation().add(1, -10, -1).getBlock().setType(Material.LAVA);
            target.getLocation().add(0, -10, -1).getBlock().setType(Material.LAVA);
            target.getLocation().add(-1, -10, -1).getBlock().setType(Material.LAVA);
            target.getLocation().add(1, -10, 1).getBlock().setType(Material.LAVA);
            target.getLocation().add(-1, -10, 0).getBlock().setType(Material.LAVA);
            target.getLocation().add(-1, -10, 1).getBlock().setType(Material.LAVA);
            target.getLocation().add(0, -9, 0).getBlock().setType(Material.COBWEB);
            target.getLocation().add(0, -9, 1).getBlock().setType(Material.COBWEB);
            target.getLocation().add(1, -9, 0).getBlock().setType(Material.COBWEB);
            target.getLocation().add(1, -9, -1).getBlock().setType(Material.COBWEB);
            target.getLocation().add(0, -9, -1).getBlock().setType(Material.COBWEB);
            target.getLocation().add(-1, -9, -1).getBlock().setType(Material.COBWEB);
            target.getLocation().add(1, -9, 1).getBlock().setType(Material.COBWEB);
            target.getLocation().add(-1, -9, 0).getBlock().setType(Material.COBWEB);
            target.getLocation().add(-1, -9, 1).getBlock().setType(Material.COBWEB);
            target.getLocation().add(0, -8, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -8, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -8, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -8, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -8, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -8, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -8, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -8, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -8, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -7, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -7, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -7, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -7, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -7, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -7, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -7, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -7, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -7, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -6, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -6, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -6, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -6, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -6, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -6, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -6, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -6, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -6, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -5, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -5, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -5, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -5, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -5, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -5, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -5, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -5, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -5, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -4, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -4, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -4, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -4, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -4, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -4, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -4, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -4, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -4, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -3, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -3, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -3, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -3, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -3, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -3, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -3, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -3, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -3, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -3, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -2, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -2, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -2, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -2, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -2, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -2, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -1, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -1, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -1, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, -1, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -1, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, -1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -1, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, -1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 0, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 0, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 0, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 0, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 0, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 0, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 0, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 0, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 1, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 1, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 1, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 1, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 1, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 1, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 2, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 2, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 2, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 2, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 2, -1).getBlock().setType(Material.AIR);
            target.getLocation().add(1, 2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 2, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(-1, 2, 1).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 1, 0).getBlock().setType(Material.AIR);
            target.getLocation().add(0, 0, 0).getBlock().setType(Material.AIR);
        }
    }

    public String getName() {
        return "Cobweb Lava Trap";
    }
}